language: node_js
sudo: false
node_js:
  - 8
  - 6
  - 4
notifications:
  email: false
cache:
  directories:
    - $HOME/.npm
    - node_modules
env:
  - COVERALLS_REPO_TOKEN=uUEysA0ilWayAooW7O4FRg6evrjnu6xyV